---
# tasks file for drupsible.xdebug
- name: Install php5-dev package
  package:
    name: 'php5-dev'
    state: 'latest'
  notify: 'Restart php5-fpm'

- name: Install xdebug
  pear: 
    name: "pecl/xdebug" 
    state: present

- name: Create xdebug.ini
  template:
    src: 'xdebug.ini.j2'
    dest: '/etc/php5/mods-available/xdebug.ini'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Configure xdebug.ini for FPM
  file:
    src: "/etc/php5/mods-available/xdebug.ini"
    dest: "/etc/php5/fpm/conf.d/20-xdebug.ini"
    state: link
  notify: 'Restart php5-fpm'

- name: Configure xdebug.ini for CLI
  file:
    src: "/etc/php5/mods-available/xdebug.ini"
    dest: "/etc/php5/cli/conf.d/20-xdebug.ini"
    state: link
